odata <-  read.delim("c:\\local\\household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?")
odata <-subset(odata,Date=="1/2/2007" | Date=="2/2/2007")
odata$Date <- strptime(paste(odata$Date,odata$Time),"%d/%m/%Y %H:%M:%S")
odata$Global_active_power <- as.numeric(odata$Global_active_power)

png(filename = "c:\\local\\Plot4.png",width = 480,height = 480,units = "px")
par(mfrow=c(2,2))
plot(odata$Date,odata$Global_active_power,type="l",ylab="Global Active Power",col="black",xlab="")
plot(odata$Date,odata$Voltage,type="l",ylab="Voltage",col="black",xlab="Datetime")
plot(odata$Date,odata$Sub_metering_1,type="n",ylab="Energy sub metering",xlab="")
lines(odata$Date,odata$Sub_metering_1,col="black",pch=22)
lines(odata$Date,odata$Sub_metering_2,col="red",pch=22)
lines(odata$Date,odata$Sub_metering_3,col="blue",pch=22)
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(odata$Date,odata$Global_reactive_power,type="l",col="black",xlab="Datetime")
dev.off()